# Generated by Django 3.1.7 on 2021-03-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines1', '0002_auto_20210319_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=30)),
                ('Message', models.CharField(max_length=30, null=True)),
                ('Contact', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
